name: CI/CD

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      go-version: 1.23
  build:
    uses: ./.github/workflows/build.yml
    with:
      go-version: 1.23
  test:
    uses: ./.github/workflows/test.yml
    with:
      go-version: 1.23
    needs: build
