name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      go-version: 1.23
  build:
    uses: ./.github/workflows/build.yml
    with:
      go-version: 1.23
