name: Test

on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
        description: 'The version of Go to use for the action.'

permissions:
  contents: read

jobs:
  test:
    name: Terraform Provider Acceptance Tests
    runs-on: ubuntu-latest
    env:
      VAULTWARDEN_ADMIN_TOKEN: admin_token
      VAULTWARDEN_EMAIL: test@example.com
      VAULTWARDEN_MASTER_PASSWORD: test-password-123!
    services:
      vaultwarden:
        image: vaultwarden/server:${{ matrix.vaultwarden_version }}-alpine
        env:
          ROCKET_PORT: "8000"
          ADMIN_TOKEN: ${{ env.VAULTWARDEN_ADMIN_TOKEN }}
          ADMIN_RATELIMIT_MAX_BURST: "1000"
          ADMIN_RATELIMIT_SECONDS: "10"
          LOGIN_RATELIMIT_MAX_BURST: "1000"
          LOGIN_RATELIMIT_SECONDS: "10"
        ports:
          - 8000:8000
        volumes:
          - /tmp/vaultwarden:/data
        options: --health-cmd="curl --fail http://localhost:8000/alive" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        terraform_version:
          - '1.8.*'
          - '1.9.*'
        vaultwarden_version:
          - 1.32.5
          - 1.31.0
          - 1.30.5
          - 1.29.2
          - 1.28.1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false
          terraform_version: ${{ matrix.terraform_version }}
      - name: Get dependencies
        run: make vendor
      - name: Terraform Acceptance Tests
        timeout-minutes: 10
        env:
          VW_TEST_URL: http://localhost:8000
        run: make testacc
